; PlatformIO Project Configuration File
; alarm_apd — ESP32 APD Alarm Node

[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM8
upload_speed = 921600
monitor_port = COM8
monitor_speed = 115200

; Deep library dependency resolution (fixes SPIFFS not found in ESP8266Audio)
lib_ldf_mode = deep+

; Build flags
build_flags = -DBOARD_HAS_PSRAM=0

; Library dependencies
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5
    earlephilhower/ESP8266Audio@^1.9.7

; SPIFFS partition for audio file
board_build.filesystem = spiffs
